### ISSUE TITLE
Add `Alert` Component

### ISSUE THREAD

**Issue by SimeonC** [tablecheck/tablekit#108]
**Location**: `system/react/src/components/Alert.ts`
**Exports**: `classySelector = '.alert'` `Alert = styled.div`
**Designs**: https://www.figma.com/file/W3hxWj6VZydNaNGJSGxRsV/TableKit-Components-(3.0)?node-id=1635%3A4909
**Other Notes**:
- Needs a storybook - single story inside file with all the variants.
- Again we want this to be as "automatic" as possible, so leverage `css-grid` to the max. The docs for this are probably going to be a bit difficult.

```scss
.alert {
  display: grid;
  grid-template-areas: `icon content close`;

  .alert-close { grid-area: close; }
  .alert-icon { grid-area: icon: }

  & > :not(.alert-close):not(.alert-icon) { grid-area: content; }
}
```
