### ISSUE TITLE
Add `Banner` Component

### ISSUE THREAD

**Issue by SimeonC** [tablecheck/tablekit#109]
**Location**: `system/react/src/components/Banner.ts`
**Exports**: `classySelector = '.banner'` `Banner = styled.div`
**Designs**: https://www.figma.com/file/W3hxWj6VZydNaNGJSGxRsV/TableKit-Components-(3.0)?node-id=1879%3A82816
**Other Notes**:
- Needs a storybook - single story inside file with all the variants.
- Again we want this to be as "automatic" as possible, so leverage `css-grid` to the max. The docs for this are probably going to be a bit difficult.

```scss
.banner {
  display: grid;
  grid-template-areas: `icon title close` `icon content content` `icon actions actions`;

  .banner-close { grid-area: close; }
  .banner-icon { grid-area: icon; }
  .banner-title { grid-area: title; }
  .banner-content { grid-area: content; }
  .banner-actions { grid-area: actions; }
}
```
